import type { AvailableSlot } from '@sawaa/shared';
import { publicFetch } from '@/lib/public-fetch';

/**
 * Booking input for an AUTHENTICATED client. The client identity is taken from
 * the httpOnly session cookie (`client_access_token`) by the backend
 * `ClientSessionGuard` — never from the request body. The previous guest path
 * (raw name/phone/email + OTP session token) has been removed.
 */
export interface AuthedBookingPayload {
  serviceId: string;
  employeeId: string;
  branchId: string;
  startsAt: string;
  /** Specific duration/price option chosen for the service */
  durationOptionId?: string;
  /** Delivery channel (IN_PERSON or ONLINE) */
  deliveryType?: 'IN_PERSON' | 'ONLINE';
  /** Legacy booking type — prefer deliveryType for new code */
  bookingType?: 'INDIVIDUAL' | 'ONLINE' | 'WALK_IN' | 'GROUP';
  couponCode?: string;
  notes?: string;
}

/**
 * The create-booking handler returns the persisted booking row plus the
 * generated invoice id. We only consume `id` (booking id) and `invoiceId`.
 */
export interface AuthedBookingResponse {
  id: string;
  invoiceId: string | null;
}

export interface PublicBranch {
  id: string;
  nameAr: string;
  nameEn: string | null;
  city: string | null;
  addressAr: string | null;
}

/** Backend public endpoints sometimes return `{ data: T }`, sometimes `T` directly. */
function unwrap<T>(json: unknown): T {
  if (json && typeof json === 'object' && 'data' in json) {
    return (json as { data: T }).data;
  }
  return json as T;
}

export async function getPublicBranches(): Promise<PublicBranch[]> {
  const json = await publicFetch<unknown>('/public/branches', { cache: 'no-store' });
  return unwrap<PublicBranch[]>(json);
}

export interface AvailabilityDay {
  date: string;
  hasSlots: boolean;
}

export async function getPublicAvailabilityDays(
  employeeId: string,
  opts: { serviceId?: string; branchId?: string; startDate?: string; days?: number } = {},
): Promise<AvailabilityDay[]> {
  const params = new URLSearchParams();
  if (opts.serviceId) params.set('serviceId', opts.serviceId);
  if (opts.branchId) params.set('branchId', opts.branchId);
  if (opts.startDate) params.set('startDate', opts.startDate);
  if (opts.days) params.set('days', String(opts.days));
  const qs = params.toString();
  const json = await publicFetch<unknown>(
    `/public/employees/${employeeId}/availability/days${qs ? `?${qs}` : ''}`,
    { cache: 'no-store' },
  );
  return unwrap<AvailabilityDay[]>(json);
}

export async function getPublicAvailability(
  employeeId: string,
  date: string,
  serviceId?: string,
  branchId?: string,
  opts: {
    durationOptionId?: string;
    deliveryType?: 'IN_PERSON' | 'ONLINE';
    bookingType?: 'INDIVIDUAL' | 'ONLINE' | 'WALK_IN' | 'GROUP';
  } = {},
): Promise<AvailableSlot[]> {
  const params = new URLSearchParams({ date });
  if (serviceId) params.set('serviceId', serviceId);
  if (branchId) params.set('branchId', branchId);
  if (opts.durationOptionId) params.set('durationOptionId', opts.durationOptionId);
  if (opts.deliveryType) params.set('deliveryType', opts.deliveryType);
  if (opts.bookingType) params.set('bookingType', opts.bookingType);
  const json = await publicFetch<unknown>(
    `/public/employees/${employeeId}/availability?${params}`,
    { cache: 'no-store' },
  );
  return unwrap<AvailableSlot[]>(json);
}

/**
 * Create a booking for the currently-logged-in client. Authentication is the
 * httpOnly session cookie sent via `credentials: 'include'`; there is no Bearer
 * token. The backend derives `clientId` from the session.
 */
export async function createBooking(payload: AuthedBookingPayload): Promise<AuthedBookingResponse> {
  const json = await publicFetch<unknown>('/public/bookings', {
    method: 'POST',
    credentials: 'include',
    body: JSON.stringify(payload),
  });
  return unwrap<AuthedBookingResponse>(json);
}

/**
 * Initialize a Moyasar payment for the invoice generated by the booking.
 * Authenticated via the session cookie. `init-client-payment` expects an
 * `invoiceId` (not a bookingId).
 */
export async function initPayment(invoiceId: string): Promise<{ paymentId: string; redirectUrl: string }> {
  const json = await publicFetch<unknown>('/public/payments/init', {
    method: 'POST',
    credentials: 'include',
    body: JSON.stringify({ invoiceId }),
  });
  return unwrap<{ paymentId: string; redirectUrl: string }>(json);
}

// Backwards-compatible aliases for existing call sites (payment.api.ts re-export).
export { createBooking as createGuestBooking, initPayment as initGuestPayment };
