/**
 * World countries list — ordered by relevance for Saudi Arabia context:
 * 1. Gulf countries
 * 2. Arab countries
 * 3. Large expat communities in Saudi Arabia
 * 4. Rest of Asia
 * 5. Africa
 * 6. Europe
 * 7. Americas & Oceania
 */

export interface Country {
  code: string
  ar: string
  en: string
  emoji: string
}

export const COUNTRIES: Country[] = [
  // ── Gulf ──
  { code: "SA", ar: "السعودية",         en: "Saudi Arabia",       emoji: "🇸🇦" },
  { code: "AE", ar: "الإمارات",          en: "UAE",                emoji: "🇦🇪" },
  { code: "KW", ar: "الكويت",            en: "Kuwait",             emoji: "🇰🇼" },
  { code: "QA", ar: "قطر",               en: "Qatar",              emoji: "🇶🇦" },
  { code: "BH", ar: "البحرين",           en: "Bahrain",            emoji: "🇧🇭" },
  { code: "OM", ar: "عُمان",             en: "Oman",               emoji: "🇴🇲" },

  // ── Arab countries ──
  { code: "YE", ar: "اليمن",             en: "Yemen",              emoji: "🇾🇪" },
  { code: "JO", ar: "الأردن",            en: "Jordan",             emoji: "🇯🇴" },
  { code: "LB", ar: "لبنان",             en: "Lebanon",            emoji: "🇱🇧" },
  { code: "SY", ar: "سوريا",             en: "Syria",              emoji: "🇸🇾" },
  { code: "IQ", ar: "العراق",            en: "Iraq",               emoji: "🇮🇶" },
  { code: "EG", ar: "مصر",               en: "Egypt",              emoji: "🇪🇬" },
  { code: "PS", ar: "فلسطين",            en: "Palestine",          emoji: "🇵🇸" },
  { code: "SD", ar: "السودان",           en: "Sudan",              emoji: "🇸🇩" },
  { code: "LY", ar: "ليبيا",             en: "Libya",              emoji: "🇱🇾" },
  { code: "TN", ar: "تونس",              en: "Tunisia",            emoji: "🇹🇳" },
  { code: "DZ", ar: "الجزائر",           en: "Algeria",            emoji: "🇩🇿" },
  { code: "MA", ar: "المغرب",            en: "Morocco",            emoji: "🇲🇦" },
  { code: "MR", ar: "موريتانيا",         en: "Mauritania",         emoji: "🇲🇷" },
  { code: "SO", ar: "الصومال",           en: "Somalia",            emoji: "🇸🇴" },
  { code: "DJ", ar: "جيبوتي",            en: "Djibouti",           emoji: "🇩🇯" },
  { code: "KM", ar: "جزر القمر",         en: "Comoros",            emoji: "🇰🇲" },

  // ── Large expat communities in Saudi Arabia ──
  { code: "IN", ar: "الهند",             en: "India",              emoji: "🇮🇳" },
  { code: "PK", ar: "باكستان",           en: "Pakistan",           emoji: "🇵🇰" },
  { code: "BD", ar: "بنغلاديش",          en: "Bangladesh",         emoji: "🇧🇩" },
  { code: "PH", ar: "الفلبين",           en: "Philippines",        emoji: "🇵🇭" },
  { code: "ID", ar: "إندونيسيا",         en: "Indonesia",          emoji: "🇮🇩" },
  { code: "ET", ar: "إثيوبيا",           en: "Ethiopia",           emoji: "🇪🇹" },
  { code: "NP", ar: "نيبال",             en: "Nepal",              emoji: "🇳🇵" },
  { code: "LK", ar: "سريلانكا",          en: "Sri Lanka",          emoji: "🇱🇰" },
  { code: "MM", ar: "ميانمار",           en: "Myanmar",            emoji: "🇲🇲" },
  { code: "ER", ar: "إريتريا",           en: "Eritrea",            emoji: "🇪🇷" },
  { code: "TR", ar: "تركيا",             en: "Turkey",             emoji: "🇹🇷" },

  // ── Rest of Asia ──
  { code: "AF", ar: "أفغانستان",         en: "Afghanistan",        emoji: "🇦🇫" },
  { code: "IR", ar: "إيران",             en: "Iran",               emoji: "🇮🇷" },
  { code: "MY", ar: "ماليزيا",           en: "Malaysia",           emoji: "🇲🇾" },
  { code: "TH", ar: "تايلاند",           en: "Thailand",           emoji: "🇹🇭" },
  { code: "VN", ar: "فيتنام",            en: "Vietnam",            emoji: "🇻🇳" },
  { code: "CN", ar: "الصين",             en: "China",              emoji: "🇨🇳" },
  { code: "JP", ar: "اليابان",           en: "Japan",              emoji: "🇯🇵" },
  { code: "KR", ar: "كوريا الجنوبية",   en: "South Korea",        emoji: "🇰🇷" },
  { code: "KP", ar: "كوريا الشمالية",   en: "North Korea",        emoji: "🇰🇵" },
  { code: "MN", ar: "منغوليا",           en: "Mongolia",           emoji: "🇲🇳" },
  { code: "KZ", ar: "كازاخستان",         en: "Kazakhstan",         emoji: "🇰🇿" },
  { code: "UZ", ar: "أوزبكستان",         en: "Uzbekistan",         emoji: "🇺🇿" },
  { code: "TJ", ar: "طاجيكستان",         en: "Tajikistan",         emoji: "🇹🇯" },
  { code: "TM", ar: "تركمانستان",        en: "Turkmenistan",       emoji: "🇹🇲" },
  { code: "KG", ar: "قيرغيزستان",        en: "Kyrgyzstan",         emoji: "🇰🇬" },
  { code: "AZ", ar: "أذربيجان",          en: "Azerbaijan",         emoji: "🇦🇿" },
  { code: "AM", ar: "أرمينيا",           en: "Armenia",            emoji: "🇦🇲" },
  { code: "GE", ar: "جورجيا",            en: "Georgia",            emoji: "🇬🇪" },
  { code: "SG", ar: "سنغافورة",          en: "Singapore",          emoji: "🇸🇬" },
  { code: "BN", ar: "بروناي",            en: "Brunei",             emoji: "🇧🇳" },
  { code: "TL", ar: "تيمور الشرقية",    en: "Timor-Leste",        emoji: "🇹🇱" },
  { code: "PG", ar: "بابوا غينيا الجديدة", en: "Papua New Guinea", emoji: "🇵🇬" },
  { code: "KH", ar: "كمبوديا",           en: "Cambodia",           emoji: "🇰🇭" },
  { code: "LA", ar: "لاوس",              en: "Laos",               emoji: "🇱🇦" },
  { code: "MV", ar: "جزر المالديف",      en: "Maldives",           emoji: "🇲🇻" },
  { code: "BT", ar: "بوتان",             en: "Bhutan",             emoji: "🇧🇹" },
  { code: "CY", ar: "قبرص",              en: "Cyprus",             emoji: "🇨🇾" },

  // ── Africa ──
  { code: "NG", ar: "نيجيريا",           en: "Nigeria",            emoji: "🇳🇬" },
  { code: "KE", ar: "كينيا",             en: "Kenya",              emoji: "🇰🇪" },
  { code: "GH", ar: "غانا",              en: "Ghana",              emoji: "🇬🇭" },
  { code: "TZ", ar: "تنزانيا",           en: "Tanzania",           emoji: "🇹🇿" },
  { code: "UG", ar: "أوغندا",            en: "Uganda",             emoji: "🇺🇬" },
  { code: "ZA", ar: "جنوب أفريقيا",     en: "South Africa",       emoji: "🇿🇦" },
  { code: "CM", ar: "الكاميرون",         en: "Cameroon",           emoji: "🇨🇲" },
  { code: "CI", ar: "ساحل العاج",        en: "Ivory Coast",        emoji: "🇨🇮" },
  { code: "SN", ar: "السنغال",           en: "Senegal",            emoji: "🇸🇳" },
  { code: "ZM", ar: "زامبيا",            en: "Zambia",             emoji: "🇿🇲" },
  { code: "ZW", ar: "زيمبابوي",          en: "Zimbabwe",           emoji: "🇿🇼" },
  { code: "MZ", ar: "موزمبيق",           en: "Mozambique",         emoji: "🇲🇿" },
  { code: "MG", ar: "مدغشقر",            en: "Madagascar",         emoji: "🇲🇬" },
  { code: "CD", ar: "الكونغو الديمقراطية", en: "DR Congo",         emoji: "🇨🇩" },
  { code: "CG", ar: "الكونغو",           en: "Congo",              emoji: "🇨🇬" },
  { code: "AO", ar: "أنغولا",            en: "Angola",             emoji: "🇦🇴" },
  { code: "NA", ar: "ناميبيا",           en: "Namibia",            emoji: "🇳🇦" },
  { code: "BW", ar: "بوتسوانا",          en: "Botswana",           emoji: "🇧🇼" },
  { code: "MW", ar: "ملاوي",             en: "Malawi",             emoji: "🇲🇼" },
  { code: "RW", ar: "رواندا",            en: "Rwanda",             emoji: "🇷🇼" },
  { code: "BI", ar: "بوروندي",           en: "Burundi",            emoji: "🇧🇮" },
  { code: "SS", ar: "جنوب السودان",      en: "South Sudan",        emoji: "🇸🇸" },
  { code: "CF", ar: "أفريقيا الوسطى",   en: "Central African Rep.", emoji: "🇨🇫" },
  { code: "TD", ar: "تشاد",              en: "Chad",               emoji: "🇹🇩" },
  { code: "NE", ar: "النيجر",            en: "Niger",              emoji: "🇳🇪" },
  { code: "ML", ar: "مالي",              en: "Mali",               emoji: "🇲🇱" },
  { code: "BF", ar: "بوركينا فاسو",      en: "Burkina Faso",       emoji: "🇧🇫" },
  { code: "GN", ar: "غينيا",             en: "Guinea",             emoji: "🇬🇳" },
  { code: "GW", ar: "غينيا بيساو",       en: "Guinea-Bissau",      emoji: "🇬🇼" },
  { code: "SL", ar: "سيراليون",          en: "Sierra Leone",       emoji: "🇸🇱" },
  { code: "LR", ar: "ليبيريا",           en: "Liberia",            emoji: "🇱🇷" },
  { code: "TG", ar: "توغو",              en: "Togo",               emoji: "🇹🇬" },
  { code: "BJ", ar: "بنين",              en: "Benin",              emoji: "🇧🇯" },
  { code: "GM", ar: "غامبيا",            en: "Gambia",             emoji: "🇬🇲" },
  { code: "CV", ar: "الرأس الأخضر",     en: "Cape Verde",         emoji: "🇨🇻" },
  { code: "ST", ar: "ساو تومي وبرنسيب", en: "São Tomé & Príncipe", emoji: "🇸🇹" },
  { code: "GQ", ar: "غينيا الاستوائية", en: "Equatorial Guinea",  emoji: "🇬🇶" },
  { code: "GA", ar: "الغابون",           en: "Gabon",              emoji: "🇬🇦" },
  { code: "SC", ar: "سيشل",              en: "Seychelles",         emoji: "🇸🇨" },
  { code: "MU", ar: "موريشيوس",          en: "Mauritius",          emoji: "🇲🇺" },

  // ── Europe ──
  { code: "RU", ar: "روسيا",             en: "Russia",             emoji: "🇷🇺" },
  { code: "GB", ar: "المملكة المتحدة",   en: "United Kingdom",     emoji: "🇬🇧" },
  { code: "FR", ar: "فرنسا",             en: "France",             emoji: "🇫🇷" },
  { code: "DE", ar: "ألمانيا",           en: "Germany",            emoji: "🇩🇪" },
  { code: "IT", ar: "إيطاليا",           en: "Italy",              emoji: "🇮🇹" },
  { code: "ES", ar: "إسبانيا",           en: "Spain",              emoji: "🇪🇸" },
  { code: "PT", ar: "البرتغال",          en: "Portugal",           emoji: "🇵🇹" },
  { code: "NL", ar: "هولندا",            en: "Netherlands",        emoji: "🇳🇱" },
  { code: "BE", ar: "بلجيكا",            en: "Belgium",            emoji: "🇧🇪" },
  { code: "CH", ar: "سويسرا",            en: "Switzerland",        emoji: "🇨🇭" },
  { code: "AT", ar: "النمسا",            en: "Austria",            emoji: "🇦🇹" },
  { code: "SE", ar: "السويد",            en: "Sweden",             emoji: "🇸🇪" },
  { code: "NO", ar: "النرويج",           en: "Norway",             emoji: "🇳🇴" },
  { code: "DK", ar: "الدنمارك",          en: "Denmark",            emoji: "🇩🇰" },
  { code: "FI", ar: "فنلندا",            en: "Finland",            emoji: "🇫🇮" },
  { code: "PL", ar: "بولندا",            en: "Poland",             emoji: "🇵🇱" },
  { code: "CZ", ar: "التشيك",            en: "Czech Republic",     emoji: "🇨🇿" },
  { code: "SK", ar: "سلوفاكيا",          en: "Slovakia",           emoji: "🇸🇰" },
  { code: "HU", ar: "المجر",             en: "Hungary",            emoji: "🇭🇺" },
  { code: "RO", ar: "رومانيا",           en: "Romania",            emoji: "🇷🇴" },
  { code: "BG", ar: "بلغاريا",           en: "Bulgaria",           emoji: "🇧🇬" },
  { code: "GR", ar: "اليونان",           en: "Greece",             emoji: "🇬🇷" },
  { code: "HR", ar: "كرواتيا",           en: "Croatia",            emoji: "🇭🇷" },
  { code: "RS", ar: "صربيا",             en: "Serbia",             emoji: "🇷🇸" },
  { code: "BA", ar: "البوسنة والهرسك",   en: "Bosnia & Herzegovina", emoji: "🇧🇦" },
  { code: "ME", ar: "الجبل الأسود",      en: "Montenegro",         emoji: "🇲🇪" },
  { code: "MK", ar: "مقدونيا الشمالية", en: "North Macedonia",    emoji: "🇲🇰" },
  { code: "AL", ar: "ألبانيا",           en: "Albania",            emoji: "🇦🇱" },
  { code: "SI", ar: "سلوفينيا",          en: "Slovenia",           emoji: "🇸🇮" },
  { code: "UA", ar: "أوكرانيا",          en: "Ukraine",            emoji: "🇺🇦" },
  { code: "BY", ar: "بيلاروسيا",         en: "Belarus",            emoji: "🇧🇾" },
  { code: "MD", ar: "مولدوفا",           en: "Moldova",            emoji: "🇲🇩" },
  { code: "LT", ar: "ليتوانيا",          en: "Lithuania",          emoji: "🇱🇹" },
  { code: "LV", ar: "لاتفيا",            en: "Latvia",             emoji: "🇱🇻" },
  { code: "EE", ar: "إستونيا",           en: "Estonia",            emoji: "🇪🇪" },
  { code: "IE", ar: "أيرلندا",           en: "Ireland",            emoji: "🇮🇪" },
  { code: "IS", ar: "آيسلندا",           en: "Iceland",            emoji: "🇮🇸" },
  { code: "LU", ar: "لوكسمبورغ",         en: "Luxembourg",         emoji: "🇱🇺" },
  { code: "MT", ar: "مالطا",             en: "Malta",              emoji: "🇲🇹" },

  // ── Americas ──
  { code: "US", ar: "الولايات المتحدة",  en: "United States",      emoji: "🇺🇸" },
  { code: "CA", ar: "كندا",              en: "Canada",             emoji: "🇨🇦" },
  { code: "MX", ar: "المكسيك",           en: "Mexico",             emoji: "🇲🇽" },
  { code: "BR", ar: "البرازيل",          en: "Brazil",             emoji: "🇧🇷" },
  { code: "AR", ar: "الأرجنتين",         en: "Argentina",          emoji: "🇦🇷" },
  { code: "CO", ar: "كولومبيا",          en: "Colombia",           emoji: "🇨🇴" },
  { code: "CL", ar: "تشيلي",             en: "Chile",              emoji: "🇨🇱" },
  { code: "PE", ar: "بيرو",              en: "Peru",               emoji: "🇵🇪" },
  { code: "VE", ar: "فنزويلا",           en: "Venezuela",          emoji: "🇻🇪" },
  { code: "EC", ar: "الإكوادور",         en: "Ecuador",            emoji: "🇪🇨" },
  { code: "BO", ar: "بوليفيا",           en: "Bolivia",            emoji: "🇧🇴" },
  { code: "PY", ar: "باراغواي",          en: "Paraguay",           emoji: "🇵🇾" },
  { code: "UY", ar: "أوروغواي",          en: "Uruguay",            emoji: "🇺🇾" },
  { code: "GY", ar: "غيانا",             en: "Guyana",             emoji: "🇬🇾" },
  { code: "SR", ar: "سورينام",           en: "Suriname",           emoji: "🇸🇷" },
  { code: "CU", ar: "كوبا",              en: "Cuba",               emoji: "🇨🇺" },
  { code: "DO", ar: "الدومينيكان",       en: "Dominican Republic", emoji: "🇩🇴" },
  { code: "HT", ar: "هايتي",             en: "Haiti",              emoji: "🇭🇹" },
  { code: "JM", ar: "جامايكا",           en: "Jamaica",            emoji: "🇯🇲" },
  { code: "TT", ar: "ترينيداد وتوباغو",  en: "Trinidad & Tobago",  emoji: "🇹🇹" },
  { code: "GT", ar: "غواتيمالا",         en: "Guatemala",          emoji: "🇬🇹" },
  { code: "HN", ar: "هندوراس",           en: "Honduras",           emoji: "🇭🇳" },
  { code: "SV", ar: "السلفادور",         en: "El Salvador",        emoji: "🇸🇻" },
  { code: "NI", ar: "نيكاراغوا",         en: "Nicaragua",          emoji: "🇳🇮" },
  { code: "CR", ar: "كوستاريكا",         en: "Costa Rica",         emoji: "🇨🇷" },
  { code: "PA", ar: "بنما",              en: "Panama",             emoji: "🇵🇦" },

  // ── Oceania ──
  { code: "AU", ar: "أستراليا",          en: "Australia",          emoji: "🇦🇺" },
  { code: "NZ", ar: "نيوزيلندا",         en: "New Zealand",        emoji: "🇳🇿" },
  { code: "FJ", ar: "فيجي",              en: "Fiji",               emoji: "🇫🇯" },
]
