export enum OtpChannel {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
}

export enum OtpPurpose {
  GUEST_BOOKING = 'GUEST_BOOKING',
  CLIENT_LOGIN = 'CLIENT_LOGIN',
  CLIENT_PASSWORD_RESET = 'CLIENT_PASSWORD_RESET',
  MOBILE_REGISTER = 'MOBILE_REGISTER',
  MOBILE_LOGIN = 'MOBILE_LOGIN',
  DASHBOARD_LOGIN = 'DASHBOARD_LOGIN',
}