-- Add BOOKING_CREATED and PAYMENT_COMPLETED to NotificationType enum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BOOKING_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYMENT_COMPLETED';
