#!/bin/bash
echo "=== Sawaa Production Secrets ==="
echo ""
echo "JWT_ACCESS_SECRET=$(openssl rand -base64 32)"
echo "JWT_REFRESH_SECRET=$(openssl rand -base64 32)"
echo "JWT_CLIENT_ACCESS_SECRET=$(openssl rand -base64 32)"
echo "JWT_CLIENT_REFRESH_SECRET=$(openssl rand -base64 32)"
echo "MOYASAR_ENCRYPTION_KEY=$(openssl rand -base64 32)"
echo "SMS_PROVIDER_ENCRYPTION_KEY=$(openssl rand -base64 32)"
echo "ZOOM_PROVIDER_ENCRYPTION_KEY=$(openssl rand -base64 32)"
echo "EMAIL_PROVIDER_ENCRYPTION_KEY=$(openssl rand -base64 32)"
echo "MINIO_ACCESS_KEY=$(openssl rand -base64 16 | tr -d '=')"
echo "MINIO_SECRET_KEY=$(openssl rand -base64 32)"
echo ""
echo "Copy these values into Dokploy Environment Variables"
