#!/bin/bash
echo "=== Sawaa Production Secrets ==="
echo ""
echo "JWT_ACCESS_SECRET=$(openssl rand -base64 32)"
echo "JWT_REFRESH_SECRET=$(openssl rand -base64 32)"
echo "JWT_CLIENT_ACCESS_SECRET=$(openssl rand -base64 32)"
echo "JWT_CLIENT_REFRESH_SECRET=$(openssl rand -base64 32)"
echo "MOYASAR_ENCRYPTION_KEY=$(openssl rand -base64 32)"
echo "SMS_PROVIDER_ENCRYPTION_KEY=$(openssl rand -base64 32)"
echo "ZOOM_PROVIDER_ENCRYPTION_KEY=$(openssl rand -base64 32)"
echo "EMAIL_PROVIDER_ENCRYPTION_KEY=$(openssl rand -base64 32)"
echo "MINIO_ACCESS_KEY=$(openssl rand -base64 16 | tr -d '=')"
echo "MINIO_SECRET_KEY=$(openssl rand -base64 32)"
echo "JWT_OTP_SECRET=$(openssl rand -base64 32)"
echo "SUPER_ADMIN_PASSWORD=$(openssl rand -base64 24)"
echo "INTERNAL_METRICS_TOKEN=$(openssl rand -hex 32)"
echo "BACKUP_ENCRYPTION_KEY=$(openssl rand -base64 32)"
# PLATFORM_SETTINGS_KEY is hex-decoded (32 bytes = 64 hex chars), not base64.
echo "PLATFORM_SETTINGS_KEY=$(openssl rand -hex 32)"
echo ""
echo "Copy these values into Dokploy Environment Variables"
