// whatsapp-webhook-verifier — verifies Evolution API's short-lived webhook JWT.
//
// The dashboard generates a webhookSecret (write-only field) that is encrypted
// at rest under the WhatsApp encryption key. This handler:
//
//   1. Loads the singleton config from the DB (system context).
//   2. Decrypts the stored webhook secret.
//   3. Verifies the HS256 JWT from the Authorization bearer header.
//   4. Validates expiry and Evolution's app/action claims.
//   5. Pins the payload instance name to the configured instance.
//
// SECURITY:
//   - We never log the decrypted secret.
//   - All compares use crypto.timingSafeEqual to prevent timing leaks.
//   - We reject any payload whose body or signature is missing/empty.
//   - We reject when no webhookSecret is configured so a forgotten
//     configuration cannot silently fall back to a permissive default.

import { BadRequestException, Injectable, Logger, UnauthorizedException } from "@nestjs/common";
import { createHmac, timingSafeEqual } from "crypto";
import { PrismaService } from "../../../../infrastructure/database";
import { WhatsappCredentialsService } from "../../../../infrastructure/whatsapp/whatsapp-credentials.service";
import { DEFAULT_ORG_ID } from "../../../../common/constants";

export interface WebhookVerifyInput {
  /** Raw request body bytes; required so empty requests fail before processing. */
  rawBody: string;
  /** Authorization: Bearer <JWT>, generated by Evolution when jwt_key is configured. */
  authorization: string | undefined;
  /** Instance name as declared in the payload — pinned to the configured one. */
  payloadInstance?: string | undefined;
}

export interface WebhookVerifyResult {
  ok: true;
  configId: string;
  instanceName: string;
}

interface EvolutionWebhookClaims {
  app?: unknown;
  action?: unknown;
  exp?: unknown;
  iat?: unknown;
}

@Injectable()
export class WhatsappWebhookVerifier {
  private readonly logger = new Logger(WhatsappWebhookVerifier.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly credentials: WhatsappCredentialsService,
  ) {}

  async verify(input: WebhookVerifyInput): Promise<WebhookVerifyResult> {
    if (!input.rawBody) {
      throw new BadRequestException("Missing request body");
    }
    const token = this.extractBearerToken(input.authorization);
    if (!token) {
      throw new UnauthorizedException("Missing webhook token");
    }

    const config = await this.prisma.whatsappAgentConfig.findFirst({
      select: {
        id: true,
        evolutionInstanceName: true,
        webhookSecretEnc: true,
        isActive: true,
      },
    });
    if (!config || !config.isActive) {
      throw new UnauthorizedException("WhatsApp agent is not configured");
    }
    if (!config.webhookSecretEnc) {
      throw new UnauthorizedException("Webhook secret is not configured");
    }

    let secret: string;
    try {
      const decrypted = this.credentials.decrypt<{ webhookSecret?: string }>(
        config.webhookSecretEnc,
        DEFAULT_ORG_ID,
      );
      if (!decrypted.webhookSecret) {
        throw new Error("webhookSecret missing in decrypted payload");
      }
      secret = decrypted.webhookSecret;
    } catch (e: unknown) {
      this.logger.warn(
        `Failed to decrypt webhook secret: ${e instanceof Error ? e.message : "unknown"}`,
      );
      throw new UnauthorizedException("Webhook secret is invalid");
    }

    this.verifyToken(token, secret);

    if (
      config.evolutionInstanceName &&
      input.payloadInstance !== config.evolutionInstanceName
    ) {
      this.logger.warn(
        `Webhook instance mismatch: configured=${config.evolutionInstanceName}`,
      );
      throw new UnauthorizedException("Webhook instance mismatch");
    }

    return {
      ok: true,
      configId: config.id,
      instanceName: config.evolutionInstanceName ?? "",
    };
  }

  private extractBearerToken(authorization: string | undefined): string | null {
    if (!authorization) return null;
    const match = /^Bearer\s+([^\s]+)$/i.exec(authorization.trim());
    return match?.[1] ?? null;
  }

  private verifyToken(token: string, secret: string): EvolutionWebhookClaims {
    try {
      const parts = token.split(".");
      if (parts.length !== 3 || !parts[0] || !parts[1] || !parts[2]) {
        throw new Error("malformed token");
      }
      const header = JSON.parse(Buffer.from(parts[0], "base64url").toString("utf8")) as {
        alg?: unknown;
        typ?: unknown;
      };
      if (header.alg !== "HS256" || (header.typ !== undefined && header.typ !== "JWT")) {
        throw new Error("unsupported token algorithm");
      }

      const expected = createHmac("sha256", secret)
        .update(`${parts[0]}.${parts[1]}`)
        .digest();
      const supplied = Buffer.from(parts[2], "base64url");
      if (expected.length !== supplied.length || !timingSafeEqual(expected, supplied)) {
        throw new Error("signature mismatch");
      }

      const claims = JSON.parse(Buffer.from(parts[1], "base64url").toString("utf8")) as EvolutionWebhookClaims;
      const now = Math.floor(Date.now() / 1000);
      if (typeof claims.exp !== "number" || claims.exp <= now) {
        throw new UnauthorizedException("Webhook token expired");
      }
      if (
        claims.app !== "evolution" ||
        claims.action !== "webhook" ||
        typeof claims.iat !== "number" ||
        claims.iat > now + 30
      ) {
        throw new Error("invalid claims");
      }
      return claims;
    } catch (error: unknown) {
      if (error instanceof UnauthorizedException) throw error;
      throw new UnauthorizedException("Invalid webhook token");
    }
  }
}
